title: Peter Cho
description: Blog

url: http://chodragon9.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 20

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Tags
   url: /tags

social:
   github: ChoDragon9
   email: 04whdydrn30@naver.com
