title: Peter Cho
description: Blog

url: http://chodragon9.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 20

navigation:
 - title: 홈
   url: /
 - title: 카테고리
    url: /category
 - title: 태그
   url: /tags
 - title: 내소개
   url: /about

social:
   github: ChoDragon9
   email: 04whdydrn30@naver.com

gems:
   - jekyll-sitemap
