title: Peter Cho
description: Blog

url: http://chodragon9.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 20

navigation:
 - title: Category
   url: /category
 - title: Tags
   url: /tags
 - title: About
   url: /about

social:
   github: ChoDragon9
   email: 04whdydrn30@naver.com

gems:
   - jekyll-sitemap
